### ISSUE TITLE
.expt files do not consistently point at the correct image file locations

### ISSUE THREAD

**Issue by toastisme** [dials/data#372]
* DIALS Regression Data version: v2.4.0
* Python version: 3.8.5
* Operating System: Ubuntu 18.04

### Description

`.expt` files often do not have the correct image file locations, so any tests involving accessing the images will fail. 
e.g.  `insulin_processed/*.expt` assume images are in the same directory, but they are actually in `../insulin/`. 

It's not entirely clear if it's even desirable to correct this, as then the description of how the data were obtained would not quite be correct (i.e repeating the same steps would not lead to having .expt files with the same imageset paths). But I think it's worth flagging.

### What I Did

```
>>> ExperimentListFactory.from_json_file(dials_data("insulin_processed", pathlib=True)/"refined.expt")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 767, in from_json_file
    return ExperimentListFactory.from_json(
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 755, in from_json
    return ExperimentListFactory.from_dict(
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 743, in from_dict
    experiments = ExperimentListDict(
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 355, in decode
    imageset = self._imageset_from_imageset_data(imageset_data, models)
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 214, in _imageset_from_imageset_data
    imageset = self._make_sequence(
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/model/experiment_list.py", line 433, in _make_sequence
    return ImageSetFactory.make_sequence(
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/imageset.py", line 597, in make_sequence
    format_class = dxtbx.format.Registry.get_format_class_for_file(
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/format/Registry.py", line 122, in get_format_class_for_file
    if scheme in format_class.schemes and format_class.understand(image_file_str):
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/format/FormatCBF.py", line 24, in understand
    with FormatCBF.open_file(image_file, "rb") as fh:
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/format/Format.py", line 565, in open_file
    return cls.get_cache_controller().check(filename_str, fh_func)
  File "/home/davidmcdonagh/work/dials/modules/dxtbx/src/dxtbx/filecache_controller.py", line 69, in check
    self._cache = dxtbx.filecache.lazy_file_cache(open_method())
FileNotFoundError: [Errno 2] No such file or directory: '/home/davidmcdonagh/work/dials/build/dials_data/insulin_processed/insulin_1_001.img'
```

**Comment by dagewa** [comment]
The relative paths in `insulin_processed/*.expt` were probably manually edited into those files. If you processed those images again I'm pretty sure you'd get absolute paths after `"template"` anyway. I can't see a great problem with editing those relative paths to point to `"../insulin_1_###.img"`. That is, I think it would at least not break anything that currently uses those datasets.
